'use client'

import React, { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { FileSpreadsheet, FileText, Calendar, Building2, Search, ChevronDown, ChevronUp, BarChart3 } from 'lucide-react'
import { useUserRole } from '@/hooks/useUserRole'
import { useSelectedRole } from '@/contexts/SelectedRoleContext'
import { RoleGuard } from '@/components/auth/RoleGuard'
import { useSearchParams, useRouter } from 'next/navigation'
import { toLocalDateString } from '@/lib/utils/dateUtils'
import {
  getExcelHeaderStyle,
  getExcelCellStyle,
  getExcelAlternateRowStyle,
  getExcelTotalStyle,
  getPDFHeaderStyles,
  getPDFBodyStyles,
  getPDFAlternateRowStyles,
  getPDFTotalRowColor,
  getPDFCellTextColor,
} from '@/lib/utils/exportStyles'
import {
  getAvailableTableWidth,
  getFontSizeForColumns,
  getProportionalColumnStyles,
  type PDFTableColumnConfig,
} from '@/lib/utils/pdfTableUtils'
import {
  enrichAsistenciasParticipantes,
  fetchAsistenciasRangoFlat,
  asistenciaCuentaParaAula,
  fetchAulasMapByIds,
  fetchEstudiantesActivosPorAulas,
  fetchEstudiantesAulaOnlyMapByIds,
} from '@/lib/reportes/asistenciasReporteQueries'
import { toast } from '@/lib/toast'

interface ReporteParticipantesPorMesProps {
  fcpId: string | null
}

interface FCPData {
  codigo: string
  nombre: string
  porcentajesPorMes: { [mes: number]: number } // mes (0-11) -> porcentaje
  numero_identificacion?: string
  razon_social?: string
}

interface DiaIncompleto {
  fecha: string
  fechaFormateada: string
  nivel: string
  aulaId: string
  /** FCP a la que pertenece el salón (necesario al ver “todas las FCPs”). */
  fcpId: string
  marcados: number
  total: number
}

interface ReporteData {
  year: number
  fcps: FCPData[]
  totalesPorMes: { [mes: number]: number } // Porcentaje total por mes
  diasIncompletos: DiaIncompleto[] // Días que no se completaron
}

function esMesFuturoDelReporte(year: number, mesIndex: number): boolean {
  const hoy = new Date()
  const añoActual = hoy.getFullYear()
  const mesActual = hoy.getMonth()
  return year > añoActual || (year === añoActual && mesIndex > mesActual)
}

function formatearCeldaPorcentajeMes(
  year: number,
  mesIndex: number,
  valor: number | undefined,
  decimales = 2
): string {
  if (esMesFuturoDelReporte(year, mesIndex)) return '-'
  if (typeof valor !== 'number' || Number.isNaN(valor)) return '-'
  return `${valor.toFixed(decimales)}%`
}

export function ReporteParticipantesPorMes({ fcpId: fcpIdProp }: ReporteParticipantesPorMesProps) {
  const searchParams = useSearchParams()
  const autoGenerate = searchParams.get('auto') === 'true'
  
  const [loading, setLoading] = useState(false)
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear())
  const [selectedFCP, setSelectedFCP] = useState<string | null>(fcpIdProp || null)
  const [userFCPs, setUserFCPs] = useState<Array<{ id: string; nombre: string }>>([])
  const [reporteData, setReporteData] = useState<ReporteData | null>(null)
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [isMobile, setIsMobile] = useState(false)
  const [mobileSearch, setMobileSearch] = useState('')
  const [mobilePage, setMobilePage] = useState(1)
  const [expandedCardId, setExpandedCardId] = useState<string | null>(null)
  const [responsable, setResponsable] = useState<{ nombre: string; email: string; rol: string } | null>(null)
  const { isFacilitador, loading: roleLoading, role } = useUserRole(selectedFCP)
  const { selectedRole } = useSelectedRole()
  const router = useRouter()

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 640)
    check()
    window.addEventListener('resize', check)
    return () => window.removeEventListener('resize', check)
  }, [])

  useEffect(() => {
    setMobilePage(1)
    setMobileSearch('')
    setExpandedCardId(null)
  }, [reporteData])

  useEffect(() => {
    const initialize = async () => {
      if (fcpIdProp) {
        setSelectedFCP(fcpIdProp)
      } else {
        await loadUserFCPs()
      }
    }
    initialize()
  }, [fcpIdProp, selectedRole?.role, selectedRole?.fcpId])

  // Generar reporte automáticamente solo cuando viene desde "Ver Detalles" (auto=true)
  useEffect(() => {
    if (autoGenerate && isFacilitador && !roleLoading && !autoGenerated && !loading && !reporteData) {
      // Pequeño delay para asegurar que todo esté listo
      const timer = setTimeout(() => {
        setAutoGenerated(true)
        generarReporte()
      }, 500)
      return () => clearTimeout(timer)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, isFacilitador, roleLoading, autoGenerated, loading, reporteData])

  const loadUserFCPs = async () => {
    try {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return

      const { data: facRow } = await supabase.from('facilitadores').select('usuario_id').eq('usuario_id', user.id).maybeSingle()
      let fcps: Array<{ id: string; nombre: string; numero_identificacion?: string }> = []
      if (facRow) {
        const { data: fcpsData } = await supabase.from('fcps').select('id, razon_social, numero_identificacion').eq('facilitador_id', user.id).eq('activa', true).order('razon_social')
        fcps = (fcpsData || []).map((f: any) => ({ id: f.id, nombre: f.razon_social || f.numero_identificacion || 'FCP', numero_identificacion: f.numero_identificacion }))
      } else {
        const { data, error } = await supabase.from('fcp_miembros').select('fcp_id, fcp:fcps(id, razon_social, numero_identificacion)').eq('usuario_id', user.id).eq('activo', true).not('fcp_id', 'is', null)
        if (error) throw error
        fcps = (data || []).filter((i: any) => i.fcp).map((i: any) => ({ id: i.fcp.id, nombre: i.fcp.razon_social || i.fcp.numero_identificacion || 'FCP', numero_identificacion: i.fcp.numero_identificacion }))
      }
      if (selectedRole?.fcpId) {
        const sole = fcps.find((f: any) => f.id === selectedRole.fcpId)
        fcps = sole ? [sole] : []
      }
      setUserFCPs(fcps)
      if (fcps.length > 0 && !selectedFCP && !fcpIdProp) {
        if (selectedRole?.fcpId && fcps.some((f: any) => f.id === selectedRole.fcpId)) setSelectedFCP(selectedRole.fcpId)
        else setSelectedFCP(fcps[0].id)
      }
    } catch (error) {
      console.error('Error loading FCPs:', error)
    }
  }

  const generarReporte = async () => {
    // Para facilitadores, no necesitamos selectedFCP ya que cargamos todas las FCPs
    if (!isFacilitador && !selectedFCP) {
      toast.warning('Selecciona FCP', 'Por favor, selecciona una FCP.')
      return
    }

    try {
      setLoading(true)
      const supabase = createClient()

      // Obtener datos del usuario actual (responsable)
      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        if (isFacilitador) {
          const { data: u } = await supabase.from('usuarios').select('nombre_completo, email').eq('id', user.id).maybeSingle()
          setResponsable({
            nombre: u?.nombre_completo || (user as any).email || '',
            email: u?.email || (user as any).email || '',
            rol: 'Facilitador',
          })
        } else if (selectedFCP) {
          // Obtener rol y datos del usuario en la FCP
          const { data: usuarioFcpData, error: usuarioFcpError } = await supabase
            .from('fcp_miembros')
            .select(`
              rol,
              usuario:usuarios(nombre_completo, email)
            `)
            .eq('usuario_id', user.id)
            .eq('fcp_id', selectedFCP)
            .eq('activo', true)
            .single()

          if (!usuarioFcpError && usuarioFcpData) {
            const usuario = usuarioFcpData.usuario as any
            const rol = usuarioFcpData.rol === 'facilitador' ? 'Facilitador' : usuarioFcpData.rol === 'director' ? 'Director' : usuarioFcpData.rol === 'secretario' ? 'Secretario' : usuarioFcpData.rol === 'tutor' ? 'Tutor' : ''
            if (rol) {
              setResponsable({
                nombre: usuario?.nombre_completo || usuario?.email || user.email || '',
                email: usuario?.email || user.email || '',
                rol,
              })
            }
          }
        }
      }

      // Si el usuario es facilitador, obtener TODAS las FCPs del sistema
      // Si no es facilitador, obtener solo las FCPs del usuario
      let fcpsAConsultar: Array<{ id: string; nombre: string; numero_identificacion?: string }> = []
      
      if (isFacilitador) {
        const { data: fcpsFac, error: fcpsError } = await supabase
          .from('fcps')
          .select('id, razon_social, numero_identificacion')
          .eq('facilitador_id', user!.id)
          .eq('activa', true)
          .order('razon_social', { ascending: true })
        if (fcpsError) throw fcpsError
        fcpsAConsultar = (fcpsFac || []).map((fcp: any) => ({
          id: fcp.id,
          nombre: fcp.razon_social || fcp.numero_identificacion || 'FCP',
          numero_identificacion: fcp.numero_identificacion
        }))
      } else {
        // Usuarios no facilitadores solo ven sus FCPs
        if (fcpIdProp) {
          const { data: fcpData } = await supabase
            .from('fcps')
            .select('id, razon_social, numero_identificacion')
            .eq('id', fcpIdProp)
            .single()
          if (fcpData) {
            fcpsAConsultar = [{ id: fcpData.id, nombre: fcpData.razon_social || fcpData.numero_identificacion || 'FCP', numero_identificacion: fcpData.numero_identificacion }]
          }
        } else if (selectedFCP) {
          const { data: fcpData } = await supabase
            .from('fcps')
            .select('id, razon_social, numero_identificacion')
            .eq('id', selectedFCP)
            .single()
          if (fcpData) {
            fcpsAConsultar = [{ id: fcpData.id, nombre: fcpData.razon_social || fcpData.numero_identificacion || 'FCP', numero_identificacion: fcpData.numero_identificacion }]
          }
        } else {
          fcpsAConsultar = userFCPs.length > 0 ? userFCPs : []
        }
      }

      const fcps: FCPData[] = []
      const totalesPorMes: { [mes: number]: { asistencias: number; oportunidades: number } } = {}
      const diasIncompletosGlobales: DiaIncompleto[] = []

      // Para cada FCP, calcular porcentaje total por mes (igual que ReporteMensual)
      for (const fcp of fcpsAConsultar) {
        // Solo aulas regulares (excluir intervenciones del reporte por FCP)
        const { data: aulasData, error: aulasError } = await supabase
          .from('aulas')
          .select('id, nombre, tipo')
          .eq('fcp_id', fcp.id)
          .eq('activa', true)
          .or('tipo.eq.REGULAR,tipo.is.null')

        if (aulasError) throw aulasError

        const regularAulaIds = new Set((aulasData || []).map((a: { id: string }) => a.id))

        // Obtener TODAS las asistencias del año para esta FCP (fecha local)
        const fechaInicio = new Date(selectedYear, 0, 1)
        const fechaFin = new Date(selectedYear, 11, 31)
        const fechaInicioStr = toLocalDateString(fechaInicio)
        const fechaFinStr = toLocalDateString(fechaFin)

        const flatAnioRaw = await fetchAsistenciasRangoFlat(supabase, fcp.id, fechaInicioStr, fechaFinStr)
        const flatAnio = flatAnioRaw.filter(
          (r) => r.aula_id && regularAulaIds.has(r.aula_id)
        )
        const idsEstAnio = [...new Set(flatAnio.map((r) => r.estudiante_id))]
        const idsAulAnio = [...new Set(flatAnio.map((r) => r.aula_id).filter(Boolean))] as string[]
        const [estMapAnio, aulMapAnio] = await Promise.all([
          fetchEstudiantesAulaOnlyMapByIds(supabase, idsEstAnio),
          fetchAulasMapByIds(supabase, idsAulAnio),
        ])
        const todasAsistenciasData = enrichAsistenciasParticipantes(flatAnio, estMapAnio, aulMapAnio)

        // Obtener estudiantes activos actuales de la FCP (para meses actuales/futuros)
        const { data: estudiantesActualesData, error: estudiantesError } = await supabase
          .from('estudiantes')
          .select('id, aula_id')
          .eq('fcp_id', fcp.id)
          .eq('activo', true)

        if (estudiantesError) throw estudiantesError

        // Obtener asistencias "presente" para el cálculo
        const asistenciasPresente = todasAsistenciasData?.filter(a => a.estado === 'presente') || []

        const porcentajesPorMes: { [mes: number]: number } = {}

        // Determinar el mes actual para comparar
        const fechaActual = new Date()
        const mesActual = fechaActual.getMonth()
        const añoActual = fechaActual.getFullYear()

        // Para cada mes del año
        for (let mes = 0; mes < 12; mes++) {
          // Determinar si este mes es anterior al actual
          const esMesAnterior = selectedYear < añoActual || (selectedYear === añoActual && mes < mesActual)

          // Rango del mes en formato YYYY-MM-DD (evita problemas de timezone al filtrar)
          const mesInicioDate = new Date(selectedYear, mes, 1)
          const mesFinDate = new Date(selectedYear, mes + 1, 0)
          const mesInicioStr = toLocalDateString(mesInicioDate)
          const mesFinStr = toLocalDateString(mesFinDate)

          let totalAsistenPromed = 0
          let totalOportunidadesAsistencia = 0

          // Obtener aulas según el mes consultado
          let aulasParaMes: any[] = []

          if (esMesAnterior) {
            // Para meses anteriores, obtener aulas únicas de las asistencias de ese mes específico
            const asistenciasDelMes = todasAsistenciasData?.filter((a: any) => {
              const fechaStr = a.fecha
              return fechaStr >= mesInicioStr && fechaStr <= mesFinStr
            }) || []

            const aulasMap = new Map<string, any>()
            asistenciasDelMes.forEach((a: any) => {
              const aulaId = a.aula_id || a.estudiante?.aula_id
              if (aulaId && !aulasMap.has(aulaId)) {
                aulasMap.set(aulaId, {
                  id: aulaId,
                  nombre: a.aula?.nombre || 'Sin aula'
                })
              }
            })
            aulasParaMes = Array.from(aulasMap.values())
          } else {
            // Para meses actuales/futuros, usar las aulas activas de la FCP
            aulasParaMes = aulasData || []
          }

          // contar + días incompletos en paralelo; estudiantes por aula en paralelo (mes anterior)
          const totalPorAulaFechaFCP = new Map<string, number>()
          const activosPorAulaEsteMes =
            esMesAnterior && aulasParaMes.length > 0
              ? await fetchEstudiantesActivosPorAulas(
                  supabase,
                  aulasParaMes.map((a: any) => a.id),
                  mesInicioStr,
                  mesFinStr
                )
              : null

          if (aulasParaMes.length > 0) {
            const aulaIdsMes = aulasParaMes.map((a: any) => a.id)
            const [rpcContarRes, rpcDiasRes] = await Promise.all([
              esMesAnterior
                ? supabase.rpc('contar_estudiantes_por_aula_fecha', {
                    p_aula_ids: aulaIdsMes,
                    p_fecha_inicio: mesInicioStr,
                    p_fecha_fin: mesFinStr,
                  })
                : Promise.resolve({ data: [] as { aula_id: string; fecha: string; total: number }[], error: null }),
              supabase.rpc('dias_incompletos_por_aula', {
                p_aula_ids: aulaIdsMes,
                p_fecha_inicio: mesInicioStr,
                p_fecha_fin: mesFinStr,
                p_fcp_id: fcp.id,
              }),
            ])
            if (rpcContarRes.error) throw rpcContarRes.error
            if (rpcDiasRes.error) throw rpcDiasRes.error
            if (esMesAnterior) {
              ;(rpcContarRes.data || []).forEach((row: { aula_id: string; fecha: string; total: number }) => {
                const fechaStr = typeof row.fecha === 'string' ? row.fecha.split('T')[0] : row.fecha
                totalPorAulaFechaFCP.set(`${row.aula_id}|${fechaStr}`, Number(row.total) || 0)
              })
            }

            ;(rpcDiasRes.data || []).forEach(
              (row: { aula_id: string; aula_nombre: string; fecha: string; marcados: number; total: number }) => {
                const fechaStr = typeof row.fecha === 'string' ? row.fecha.split('T')[0] : row.fecha
                const [y, m, d] = fechaStr.split('-').map(Number)
                const fechaDate = new Date(y, m - 1, d)
                diasIncompletosGlobales.push({
                  fecha: fechaStr,
                  fechaFormateada: fechaDate.toLocaleDateString('es-PE', {
                    day: 'numeric',
                    month: 'long',
                    timeZone: 'America/Lima',
                  }),
                  nivel: row.aula_nombre || 'Sin aula',
                  aulaId: row.aula_id,
                  fcpId: fcp.id,
                  marcados: Number(row.marcados) || 0,
                  total: Number(row.total) || 0,
                })
              }
            )
          }

          // Obtener estudiantes según el mes consultado
          let estudiantesParaMes: any[] = []

          if (esMesAnterior) {
            // Para meses anteriores, obtener estudiantes únicos de las asistencias de ese mes específico
            const asistenciasDelMes = todasAsistenciasData?.filter((a: any) => {
              const fechaStr = a.fecha
              return fechaStr >= mesInicioStr && fechaStr <= mesFinStr
            }) || []

            const estudiantesMap = new Map<string, any>()
            asistenciasDelMes.forEach((asist: any) => {
              if (asist.estudiante && !estudiantesMap.has(asist.estudiante_id)) {
                estudiantesMap.set(asist.estudiante_id, {
                  id: asist.estudiante.id,
                  aula_id: asist.aula_id || asist.estudiante?.aula_id // Usar aula_id de la asistencia (histórica)
                })
              }
            })
            estudiantesParaMes = Array.from(estudiantesMap.values())
          } else {
            // Para meses actuales/futuros, usar estudiantes activos actuales
            estudiantesParaMes = estudiantesActualesData || []
          }

          // Procesar por aula - MISMA lógica que vista Asistencias
          for (const aula of aulasParaMes) {
            let estudiantesAula: any[] = []

            if (esMesAnterior) {
              const ids = activosPorAulaEsteMes?.get(aula.id) || []
              const estudiantesParaMesMap = new Map((estudiantesParaMes || []).map((e: any) => [e.id, e]))
              estudiantesAula = ids.map((id) =>
                estudiantesParaMesMap.get(id) || { id, aula_id: aula.id }
              )
            } else {
              estudiantesAula = estudiantesParaMes?.filter(e => e.aula_id === aula.id) || []
            }

            const registrados = estudiantesAula.length

            if (registrados === 0) continue

            const estudiantesAulaIds = new Set(estudiantesAula.map(e => e.id))
            const asistenciasDelMesAula = todasAsistenciasData?.filter((a: any) => {
              const fechaStr = a.fecha
              return (
                fechaStr >= mesInicioStr &&
                fechaStr <= mesFinStr &&
                estudiantesAulaIds.has(a.estudiante_id) &&
                asistenciaCuentaParaAula(a, aula.id)
              )
            }) || []
            const asistenciasPorFecha = new Map<string, Set<string>>()
            asistenciasDelMesAula.forEach((asistencia: any) => {
              const fecha = asistencia.fecha
              if (!asistenciasPorFecha.has(fecha)) asistenciasPorFecha.set(fecha, new Set())
              asistenciasPorFecha.get(fecha)!.add(asistencia.estudiante_id)
            })

            // Días completos: solo cuenta un día cuando TODOS los estudiantes tienen registro
            // (presente, faltó o permiso). Si algún estudiante no tiene estado ese día, no cuenta.
            let diasDeClases = 0
            let oportunidadesAula = 0 // Suma de registradosEnFecha por cada día completo
            const fechasDiasCompletos = new Set<string>()
            const diasDelMes = new Date(selectedYear, mes + 1, 0).getDate()

            for (let dia = 1; dia <= diasDelMes; dia++) {
              const fechaStr = `${selectedYear}-${String(mes + 1).padStart(2, '0')}-${String(dia).padStart(2, '0')}`
              const estudiantesConAsistencia = asistenciasPorFecha.get(fechaStr) || new Set()
              const marcados = estudiantesConAsistencia.size // Estudiantes con estado (presente/faltó/permiso)

              // Para meses anteriores: usar RPC para el total correcto por fecha (evita RLS)
              const registradosEnFecha = esMesAnterior && totalPorAulaFechaFCP.size > 0
                ? (totalPorAulaFechaFCP.get(`${aula.id}|${fechaStr}`) ?? registrados)
                : registrados

              // Solo día completo: todos tienen registro; si falta alguno, no cuenta
              if (marcados === registradosEnFecha && registradosEnFecha > 0) {
                diasDeClases++
                oportunidadesAula += registradosEnFecha
                fechasDiasCompletos.add(fechaStr)
              }
            }

            // Contar asistencias "presente" para estudiantes de esta aula SOLO de días completos
            const asistenciasAula = asistenciasPresente?.filter((a: any) => {
              if (!estudiantesAulaIds.has(a.estudiante_id)) return false
              const [year, monthNum, day] = a.fecha.split('-').map(Number)
              const fechaDate = new Date(year, monthNum - 1, day)
              const esDelMes = fechaDate.getFullYear() === selectedYear && fechaDate.getMonth() === mes
              return esDelMes && fechasDiasCompletos.has(a.fecha)
            }) || []
            const asistenPromed = asistenciasAula.length

            // Calcular oportunidades: con RPC usamos la suma por día; si no, diasDeClases * registrados
            const oportunidadesAsistencia = esMesAnterior && totalPorAulaFechaFCP.size > 0
              ? oportunidadesAula
              : diasDeClases * registrados
            
            // Acumular totales
            totalAsistenPromed += asistenPromed
            totalOportunidadesAsistencia += oportunidadesAsistencia
          }

          // Calcular porcentaje total de la FCP para este mes (igual que ReporteMensual)
          const porcentaje =
            totalOportunidadesAsistencia > 0
              ? (totalAsistenPromed / totalOportunidadesAsistencia) * 100
              : 0
          porcentajesPorMes[mes] = porcentaje

          // Acumular para total general por mes (si hay múltiples FCPs)
          if (!totalesPorMes[mes]) {
            totalesPorMes[mes] = { asistencias: 0, oportunidades: 0 }
          }
          totalesPorMes[mes].asistencias += totalAsistenPromed
          totalesPorMes[mes].oportunidades += totalOportunidadesAsistencia
        }

        // Usar directamente el número de identificación de la FCP
        const numeroIdentificacion = (fcp as any).numero_identificacion || fcp.id.substring(0, 6).toUpperCase() || 'FCP'

        fcps.push({
          codigo: numeroIdentificacion,
          nombre: fcp.razon_social || (fcp as any).numero_identificacion || 'FCP',
          porcentajesPorMes,
          numero_identificacion: (fcp as any).numero_identificacion,
          razon_social: fcp.razon_social,
        })
      }

      // Calcular porcentajes totales por mes
      const porcentajesTotalesPorMes: { [mes: number]: number } = {}
      for (let mes = 0; mes < 12; mes++) {
        const totalMes = totalesPorMes[mes]
        if (totalMes && totalMes.oportunidades > 0) {
          porcentajesTotalesPorMes[mes] =
            (totalMes.asistencias / totalMes.oportunidades) * 100
        } else {
          porcentajesTotalesPorMes[mes] = 0
        }
      }

      setReporteData({
        year: selectedYear,
        fcps,
        totalesPorMes: porcentajesTotalesPorMes,
        diasIncompletos: diasIncompletosGlobales.sort((a, b) => a.fecha.localeCompare(b.fecha)),
      })
      
      // Mostrar días incompletos de forma destacada en la consola
      console.log('')
      console.log('═══════════════════════════════════════════════════════════')
      console.log('📊📊📊 RESUMEN DE DÍAS INCOMPLETOS (FCPs por Mes) 📊📊📊')
      console.log('═══════════════════════════════════════════════════════════')
      console.log(`Total de días incompletos detectados: ${diasIncompletosGlobales.length}`)
      console.log('')
      
      if (diasIncompletosGlobales.length > 0) {
        console.log('⚠️⚠️⚠️ LISTA DE DÍAS INCOMPLETOS ⚠️⚠️⚠️')
        console.log('')
        diasIncompletosGlobales.forEach((dia, index) => {
          const faltantes = dia.total - dia.marcados
          const porcentajeCompleto = ((dia.marcados / dia.total) * 100).toFixed(1)
          console.log(`${index + 1}. ${dia.fechaFormateada} - ${dia.nivel}`)
          console.log(`   📅 Fecha: ${dia.fecha}`)
          console.log(`   👥 Marcados: ${dia.marcados} / ${dia.total} estudiantes`)
          console.log(`   ❌ Faltantes: ${faltantes} estudiantes`)
          console.log(`   📊 Porcentaje completo: ${porcentajeCompleto}%`)
          console.log('')
        })
      } else {
        console.log('✅ No se detectaron días incompletos')
        console.log('   (Todos los días tienen asistencia completa)')
        console.log('')
      }
      
      console.log('═══════════════════════════════════════════════════════════')
      console.log('')
    } catch (error) {
      console.error('Error generating report:', error)
      toast.error('Error al generar el reporte', 'Intenta nuevamente.')
    } finally {
      setLoading(false)
    }
  }

  const exportarExcel = async () => {
    if (!reporteData) return

    try {
      const XLSX = await import('xlsx-js-style')

      const wb = XLSX.utils.book_new()

      const monthNames = [
        'ENERO',
        'FEBRERO',
        'MARZO',
        'ABRIL',
        'MAYO',
        'JUNIO',
        'JULIO',
        'AGOSTO',
        'SEPTIEMBRE',
        'OCTUBRE',
        'NOVIEMBRE',
        'DICIEMBRE',
      ]

      // Estilos
      // Estilos con colores del tema
      const headerStyle = getExcelHeaderStyle()
      const cellStyle = getExcelCellStyle()
      const totalStyle = getExcelTotalStyle()

      const applyStyle = (ws: any, range: string, style: any) => {
        const cellRange = XLSX.utils.decode_range(range)
        for (let R = cellRange.s.r; R <= cellRange.e.r; ++R) {
          for (let C = cellRange.s.c; C <= cellRange.e.c; ++C) {
            const cellAddress = XLSX.utils.encode_cell({ c: C, r: R })
            if (!ws[cellAddress]) ws[cellAddress] = { t: 's', v: '' }
            ws[cellAddress].s = style
          }
        }
      }

      // Preparar datos
      const header = ['Código', 'FCP', ...monthNames]
      const rows: any[] = reporteData.fcps.map((fcp) => [
        fcp.codigo,
        fcp.nombre,
        ...monthNames.map((_, index) =>
          formatearCeldaPorcentajeMes(reporteData.year, index, fcp.porcentajesPorMes[index])
        ),
      ])

      // Fila de totales
      const totalRow = [
        'Total General',
        '',
        ...monthNames.map((_, index) =>
          formatearCeldaPorcentajeMes(reporteData.year, index, reporteData.totalesPorMes[index])
        ),
      ]

      const encabezado = [
        [`% de la asistencia por mes - ${reporteData.year}`],
        [`PROYECTO: TODAS LAS FCPs`, `AÑO: ${reporteData.year}`, `MES: TODOS LOS MESES`],
        ...(responsable ? [[`RESPONSABLE: ${responsable.nombre.toUpperCase()}`, `EMAIL: ${responsable.email.toUpperCase()}`, `ROL: ${responsable.rol.toUpperCase()}`]] : []),
        [],
        header,
        ...rows,
        totalRow,
      ]

      const ws = XLSX.utils.aoa_to_sheet(encabezado)

      // Aplicar estilos
      ws['A1'].s = {
        font: { bold: true, sz: 16 },
        alignment: { horizontal: 'center' },
      }

      const headerRowIndex = 4
      const headerRange = XLSX.utils.encode_range({
        s: { c: 0, r: headerRowIndex },
        e: { c: header.length - 1, r: headerRowIndex },
      })
      applyStyle(ws, headerRange, headerStyle)
      
      // Ajustar ancho de columnas
      ws['!cols'] = [
        { wch: 15 }, // Código
        { wch: 30 }, // FCP
        ...monthNames.map(() => ({ wch: 12 })), // Meses
      ]

      // Estilos para datos
      if (rows.length > 0) {
        const dataStartRow = headerRowIndex + 1
        const dataEndRow = headerRowIndex + rows.length
        const dataRange = XLSX.utils.encode_range({
          s: { c: 0, r: dataStartRow },
          e: { c: header.length - 1, r: dataEndRow },
        })
        applyStyle(ws, dataRange, cellStyle)
      }

      // Estilo para fila de totales
      const totalRowIndex = headerRowIndex + 1 + rows.length
      const totalRange = XLSX.utils.encode_range({
        s: { c: 0, r: totalRowIndex },
        e: { c: header.length - 1, r: totalRowIndex },
      })
      applyStyle(ws, totalRange, totalStyle)


      XLSX.utils.book_append_sheet(wb, ws, 'Reporte Participantes')

      const nombreArchivo = `Reporte_FCPs_por_Mes_${reporteData.year}.xlsx`
      XLSX.writeFile(wb, nombreArchivo)
    } catch (error) {
      console.error('Error exporting to Excel:', error)
      toast.error('Error al exportar a Excel', 'Intenta nuevamente.')
    }
  }

  const exportarPDF = async () => {
    if (!reporteData) return

    try {
      const jsPDF = (await import('jspdf')).default
      const autotableModule = await import('jspdf-autotable')

      let autoTable: any = null
      if (
        (autotableModule as any).autoTable &&
        typeof (autotableModule as any).autoTable === 'function'
      ) {
        autoTable = (autotableModule as any).autoTable
      } else if (
        (autotableModule as any).default &&
        typeof (autotableModule as any).default === 'function'
      ) {
        autoTable = (autotableModule as any).default
      }

      if (
        (autotableModule as any).applyPlugin &&
        typeof (autotableModule as any).applyPlugin === 'function'
      ) {
        ;(autotableModule as any).applyPlugin(jsPDF)
      }

      const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
      const pageWidth = doc.internal.pageSize.getWidth()

      const monthNames = [
        'ENERO',
        'FEBRERO',
        'MARZO',
        'ABRIL',
        'MAYO',
        'JUNIO',
        'JULIO',
        'AGOSTO',
        'SEPTIEMBRE',
        'OCTUBRE',
        'NOVIEMBRE',
        'DICIEMBRE',
      ]

      let y = 12

      // Título
      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.text(
        `% de la asistencia por mes - ${reporteData.year}`,
        pageWidth / 2,
        y,
        { align: 'center' }
      )
      y += 4

      // Información del responsable (tres columnas)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      const col1 = 20
      const col2 = pageWidth / 3 + 10
      const col3 = (pageWidth / 3) * 2 + 10
      
      doc.text(`PROYECTO: TODAS LAS FCPs`, col1, y)
      doc.text(`AÑO: ${reporteData.year}`, col2, y)
      doc.text(`MES: TODOS LOS MESES`, col3, y)
      y += 4
      if (responsable) {
        doc.text(`RESPONSABLE: ${responsable.nombre.toUpperCase()}`, col1, y)
        doc.text(`EMAIL: ${responsable.email.toUpperCase()}`, col2, y)
        doc.text(`ROL: ${responsable.rol.toUpperCase()}`, col3, y)
        y += 4
      }
      y += 4

      // Preparar datos para la tabla
      const headers: string[] = ['Código', 'FCP', ...monthNames]
      const body: any[] = reporteData.fcps.map((fcp) => [
        fcp.codigo,
        fcp.nombre,
        ...monthNames.map((_, index) =>
          formatearCeldaPorcentajeMes(reporteData.year, index, fcp.porcentajesPorMes[index])
        ),
      ])

      // Fila de totales
      const totalRow = [
        'Total General',
        '',
        ...monthNames.map((_, index) =>
          formatearCeldaPorcentajeMes(reporteData.year, index, reporteData.totalesPorMes[index])
        ),
      ]
      body.push(totalRow)

      const numCols = headers.length
      const availableWidth = getAvailableTableWidth(doc, 15)
      const fontSize = getFontSizeForColumns(numCols)
      const columnConfigs: PDFTableColumnConfig[] = [
        { type: 'compact', weight: 0.6, halign: 'left' },
        { type: 'text', weight: 1.2, halign: 'left' },
        ...monthNames.map(() => ({ type: 'compact' as const, weight: 0.5, halign: 'center' as const })),
      ]
      const columnStyles = getProportionalColumnStyles(numCols, availableWidth, columnConfigs)

      const tableOptions = {
        startY: y,
        head: [headers],
        body: body,
        theme: 'grid',
        tableWidth: availableWidth,
        margin: { left: 15, right: 15 },
        headStyles: {
          ...getPDFHeaderStyles(),
          fontSize,
          cellPadding: 2,
        },
        bodyStyles: {
          ...getPDFBodyStyles(),
          fontSize: Math.max(5, fontSize - 0.5),
          cellPadding: 1.5,
        },
        alternateRowStyles: getPDFAlternateRowStyles(),
        styles: {
          cellPadding: 1.5,
          overflow: 'linebreak',
          fontSize: Math.max(5, fontSize - 0.5),
        },
        columnStyles,
        didParseCell: function (data: any) {
          try {
            if (data.table && data.table.body) {
              const rowIndex = data.rowIndex
              if (rowIndex !== undefined && rowIndex >= 0) {
                const row = data.table.body[rowIndex]
                if (row && rowIndex === data.table.body.length - 1) {
                  data.cell.styles.fillColor = getPDFTotalRowColor()
                  data.cell.styles.fontStyle = 'bold'
                }
              }
            }
          } catch (e) {
            console.warn('Error en didParseCell:', e)
          }
        },
      }

      if (typeof (doc as any).autoTable === 'function') {
        ;(doc as any).autoTable(tableOptions)
      } else if (typeof autoTable === 'function') {
        autoTable(doc, tableOptions)
      } else {
        throw new Error(
          'autoTable no está disponible. Verifica la instalación de jspdf-autotable.'
        )
      }

      const nombreArchivo = `Reporte_FCPs_por_Mes_${reporteData.year}.pdf`
      doc.save(nombreArchivo)
    } catch (error) {
      console.error('Error exporting to PDF:', error)
      toast.error('Error al exportar a PDF', 'Intenta nuevamente.')
    }
  }

  if (!selectedFCP && userFCPs.length === 0) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-12">
          <BarChart3 className="h-12 w-12 text-muted-foreground mb-4 animate-pulse" />
          <p className="text-muted-foreground">Cargando FCPs por meses...</p>
        </CardContent>
      </Card>
    )
  }

  if (!roleLoading && !isFacilitador) {
    return (
      <Card>
        <CardContent className="flex flex-col items-center justify-center py-12">
          <p className="text-muted-foreground mb-4">
            No tienes permisos para ver este reporte. Solo los facilitadores pueden acceder a esta funcionalidad.
          </p>
        </CardContent>
      </Card>
    )
  }

  const monthNames = [
    'ENERO',
    'FEBRERO',
    'MARZO',
    'ABRIL',
    'MAYO',
    'JUNIO',
    'JULIO',
    'AGOSTO',
    'SEPTIEMBRE',
    'OCTUBRE',
    'NOVIEMBRE',
    'DICIEMBRE',
  ]

  return (
    <div>
      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Configurar Reporte de FCPs por Mes</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {!fcpIdProp && !isFacilitador && (
              <div>
                <label className="text-sm font-medium mb-2 block">FCP:</label>
                <Select
                  value={selectedFCP || ''}
                  onValueChange={(value) => setSelectedFCP(value || null)}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Seleccionar FCP">
                      {selectedFCP ? (
                        <div className="flex items-center gap-2">
                          <Building2 className="h-4 w-4" />
                          <span className="truncate">{userFCPs.find(fcp => fcp.id === selectedFCP)?.nombre || 'Seleccionar FCP'}</span>
                        </div>
                      ) : (
                        'Seleccionar FCP'
                      )}
                    </SelectValue>
                  </SelectTrigger>
                  <SelectContent>
                  {userFCPs.map((fcp) => (
                      <SelectItem key={fcp.id} value={fcp.id}>
                        <div className="flex items-center gap-2">
                          <Building2 className="h-4 w-4 flex-shrink-0" />
                          <span className="truncate">{fcp.nombre}</span>
                          {fcp.numero_identificacion && (
                            <span className="text-xs text-muted-foreground whitespace-nowrap">({fcp.numero_identificacion})</span>
                          )}
                        </div>
                      </SelectItem>
                  ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            <div>
              <label className="text-sm font-medium mb-2 block">Año:</label>
              <Input
                type="number"
                value={selectedYear}
                onChange={(e) => setSelectedYear(parseInt(e.target.value) || new Date().getFullYear())}
                className="w-full"
                min="2020"
                max="2100"
              />
            </div>
          </div>

          {isFacilitador && (
            <div className="mt-2 text-sm text-muted-foreground">
              <p>Como facilitador, el reporte incluirá todas las FCPs del sistema.</p>
            </div>
          )}

          <RoleGuard fcpId={selectedFCP} allowedRoles={['facilitador']}>
            <div className="mt-4">
              <Button onClick={generarReporte} disabled={loading || (!isFacilitador && !selectedFCP)}>
                {loading ? (
                  <>
                    <Calendar className="mr-2 h-4 w-4 animate-pulse" />
                    Generando...
                  </>
                ) : (
                  <>
                    <Calendar className="mr-2 h-4 w-4" />
                    Generar Reporte
                  </>
                )}
              </Button>
            </div>
          </RoleGuard>
        </CardContent>
      </Card>

      {reporteData && (
        <Card>
          <CardHeader>
            <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
              <div className="min-w-0 flex-1">
                <CardTitle>
                  % de la asistencia por mes - {reporteData.year}
                </CardTitle>
                {responsable && (
                  <div className="text-sm text-muted-foreground mt-1 grid grid-cols-1 gap-y-1 gap-x-8 sm:grid-cols-2 lg:grid-cols-3">
                    <p><strong>PROYECTO:</strong> TODAS LAS FCPs</p>
                    <p><strong>AÑO:</strong> {reporteData.year}</p>
                    <p><strong>MES:</strong> TODOS LOS MESES</p>
                    {responsable && (
                      <>
                        <p><strong>RESPONSABLE:</strong> {responsable.nombre.toUpperCase()}</p>
                        <p><strong>EMAIL:</strong> {responsable.email.toUpperCase()}</p>
                        <p><strong>ROL:</strong> {responsable.rol.toUpperCase()}</p>
                      </>
                    )}
                  </div>
                )}
              </div>
              <RoleGuard fcpId={selectedFCP} allowedRoles={['facilitador']}>
                <div className="flex flex-shrink-0 flex-wrap gap-2">
                  <Button variant="outline" onClick={exportarExcel}>
                    <FileSpreadsheet className="mr-2 h-4 w-4" />
                    Excel
                  </Button>
                  <Button variant="outline" onClick={exportarPDF}>
                    <FileText className="mr-2 h-4 w-4" />
                    PDF
                  </Button>
                </div>
              </RoleGuard>
            </div>
          </CardHeader>
          <CardContent>
            {/* Mensaje de días incompletos */}
            {reporteData.diasIncompletos && reporteData.diasIncompletos.length > 0 && (
              <div className="mb-4 rounded-md bg-warning/20 border border-warning/50 p-4">
                <h4 className="font-semibold text-warning-foreground mb-2">
                  ⚠️ Días con asistencia incompleta
                </h4>
                <p className="text-sm text-warning-foreground mb-2">
                  Los siguientes días no se completó la asistencia de todos los estudiantes. Estos días <strong>no se incluyen</strong> en los totales del reporte:
                </p>
                <ul className="text-sm text-warning-foreground space-y-2">
                  {reporteData.diasIncompletos.map((dia, index) => {
                    // Parsear fecha como fecha local para evitar problemas de zona horaria
                    const [year, month, day] = dia.fecha.split('-').map(Number)
                    const fechaDate = new Date(year, month - 1, day)
                    const yearForUrl = fechaDate.getFullYear()
                    const monthForUrl = fechaDate.getMonth()
                    const asistenciasUrl = `/asistencias?fcpId=${dia.fcpId || selectedRole?.fcpId || selectedFCP || ''}&aulaId=${dia.aulaId}&month=${monthForUrl}&year=${yearForUrl}&date=${dia.fecha}`
                    
                    return (
                      <li key={`${dia.fcpId}-${dia.aulaId}-${dia.fecha}-${index}`} className="flex items-center justify-between gap-3 p-2 rounded-md bg-warning/30 border border-warning/60">
                        <span className="flex-1">
                          • <strong>{dia.fechaFormateada}</strong> - Nivel: <strong>{dia.nivel}</strong> - Marcados: {dia.marcados}/{dia.total} estudiantes
                        </span>
                        <Button
                          type="button"
                          size="sm"
                          variant="outline"
                          onClick={() => router.push(asistenciasUrl)}
                          className="ml-auto text-blue-600 dark:text-blue-400 border-blue-300 dark:border-blue-700 hover:bg-blue-50 dark:hover:bg-blue-900/30 hover:text-blue-700 dark:hover:text-blue-300 whitespace-nowrap"
                        >
                          <Calendar className="h-4 w-4 mr-1.5" />
                          {role === 'facilitador' ? 'Ver asistencia' : 'Corregir asistencia'}
                        </Button>
                      </li>
                    )
                  })}
                </ul>
              </div>
            )}
            
            {isMobile ? (
              (() => {
                const monthNamesShort = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']
                const filtered = mobileSearch.trim()
                  ? reporteData.fcps.filter(
                      (f) =>
                        f.nombre.toLowerCase().includes(mobileSearch.toLowerCase()) ||
                        (f.codigo || '').toLowerCase().includes(mobileSearch.toLowerCase())
                    )
                  : reporteData.fcps
                const perPage = 8
                const totalPages = Math.max(1, Math.ceil(filtered.length / perPage))
                const display = filtered.slice((mobilePage - 1) * perPage, mobilePage * perPage)
                const avgPct = (fcp: FCPData) => {
                  const vals = Object.values(fcp.porcentajesPorMes).filter((v) => v != null && !isNaN(v))
                  return vals.length > 0 ? (vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(1) : '-'
                }
                return (
                  <div className="space-y-4">
                    <div className="relative">
                      <Input placeholder="Buscar por FCP o código..." value={mobileSearch} onChange={(e) => { setMobileSearch(e.target.value); setMobilePage(1) }} className="pl-9" />
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    </div>
                    <div className="space-y-3">
                      {display.map((fcp) => {
                        const key = fcp.codigo
                        const isExpanded = expandedCardId === key
                        return (
                          <Card key={key}>
                            <div className="p-4 cursor-pointer" onClick={() => setExpandedCardId(isExpanded ? null : key)}>
                              <div className="flex items-start justify-between gap-2">
                                <div className="min-w-0 flex-1">
                                  <p className="font-mono text-sm text-muted-foreground">{fcp.codigo}</p>
                                  <p className="font-medium">{fcp.nombre}</p>
                                  <p className="text-sm mt-1">Promedio anual: {avgPct(fcp)}%</p>
                                </div>
                                {isExpanded ? <ChevronUp className="h-4 w-4 shrink-0" /> : <ChevronDown className="h-4 w-4 shrink-0" />}
                              </div>
                              {isExpanded && (
                                <div className="mt-4 pt-3 border-t grid grid-cols-4 gap-2">
                                  {[0,1,2,3,4,5,6,7,8,9,10,11].map((mesIndex) => (
                                    <div key={mesIndex} className="text-center py-1 rounded text-xs bg-muted">
                                      <span className="block font-medium">{monthNamesShort[mesIndex]}</span>
                                      <span>
                                        {formatearCeldaPorcentajeMes(
                                          reporteData.year,
                                          mesIndex,
                                          fcp.porcentajesPorMes[mesIndex],
                                          1
                                        )}
                                      </span>
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>
                          </Card>
                        )
                      })}
                    </div>
                    {filtered.length > perPage && (
                      <div className="flex items-center justify-between pt-4 border-t">
                        <p className="text-sm text-muted-foreground">
                          {(mobilePage - 1) * perPage + 1} - {Math.min(mobilePage * perPage, filtered.length)} de {filtered.length}
                        </p>
                        <div className="flex gap-2">
                          <Button variant="outline" size="sm" disabled={mobilePage <= 1} onClick={() => setMobilePage((p) => Math.max(1, p - 1))}>Anterior</Button>
                          <Button variant="outline" size="sm" disabled={mobilePage >= totalPages} onClick={() => setMobilePage((p) => Math.min(totalPages, p + 1))}>Siguiente</Button>
                        </div>
                      </div>
                    )}
                  </div>
                )
              })()
            ) : (
            <>
            <p className="mb-2 text-xs text-muted-foreground md:hidden">Desliza para ver más columnas →</p>
            <div className="table-responsive overflow-x-auto">
              <table className="w-full border-collapse border border-border text-sm">
                <thead>
                  <tr className="bg-muted/50">
                    <th className="border border-border p-2 bg-muted/50 text-left text-foreground">
                      Código
                    </th>
                    <th className="border border-border p-2 bg-muted/50 text-left text-foreground">
                      FCP
                    </th>
                    {monthNames.map((mes) => (
                      <th
                        key={mes}
                        className="border border-border p-2 bg-muted/50 text-center text-foreground"
                      >
                        {mes}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {reporteData.fcps.map((fcp, index) => (
                    <tr
                      key={fcp.codigo}
                      className={`border-b border-border ${index % 2 === 0 ? 'bg-background' : 'bg-muted/30'} hover:bg-accent/50`}
                    >
                      <td className="border border-border p-2 font-semibold text-foreground">
                        {fcp.codigo}
                      </td>
                      <td className="border border-border p-2 text-foreground">
                        {fcp.nombre}
                      </td>
                      {monthNames.map((_, mesIndex) => (
                        <td
                          key={mesIndex}
                          className="border border-border p-2 text-center text-foreground"
                        >
                          {formatearCeldaPorcentajeMes(
                            reporteData.year,
                            mesIndex,
                            fcp.porcentajesPorMes[mesIndex]
                          )}
                        </td>
                      ))}
                    </tr>
                  ))}
                  {/* Fila de totales */}
                  <tr className="bg-accent font-bold">
                    <td className="border border-border p-2 text-foreground" colSpan={2}>
                      Total General
                    </td>
                    {monthNames.map((_, mesIndex) => (
                      <td
                        key={mesIndex}
                        className="border border-border p-2 text-center text-foreground"
                      >
                        {formatearCeldaPorcentajeMes(
                          reporteData.year,
                          mesIndex,
                          reporteData.totalesPorMes[mesIndex]
                        )}
                      </td>
                    ))}
                  </tr>
                </tbody>
              </table>
            </div>
            </>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  )
}

