#!/bin/bash

# Script para organizar capturas de pantalla del sistema
# Uso: ./scripts/tomar_capturas.sh

echo "📸 Guía para Capturas de Pantalla del Sistema"
echo "=============================================="
echo ""
echo "Este script te ayudará a organizar las capturas de pantalla."
echo ""
echo "PASOS A SEGUIR:"
echo ""
echo "1. Inicia el servidor de desarrollo:"
echo "   npm run dev"
echo ""
echo "2. Abre el navegador en: http://localhost:3000"
echo ""
echo "3. Toma las capturas en este orden:"
echo ""
echo "   AUTENTICACIÓN:"
echo "   - Login page (/login)"
echo ""
echo "   DASHBOARDS:"
echo "   - Dashboard Facilitador (/dashboard como facilitador)"
echo "   - Dashboard Director (/dashboard como director)"
echo "   - Dashboard Tutor (/dashboard como tutor)"
echo ""
echo "   GESTIÓN:"
echo "   - Lista FCPs (/fcps)"
echo "   - Crear FCP (formulario)"
echo "   - Lista Aulas (/aulas)"
echo "   - Lista Estudiantes (/estudiantes)"
echo "   - Carga Masiva Excel (diálogo)"
echo ""
echo "   ASISTENCIAS:"
echo "   - Calendario Mensual (/asistencias)"
echo "   - Registro Diario (diálogo)"
echo ""
echo "   REPORTES:"
echo "   - Reporte Mensual (/reportes?view=mensual)"
echo "   - Reporte por Nivel (/reportes?view=nivel)"
echo "   - Reporte FCPs por Mes (/reportes?view=participantes-mes)"
echo ""
echo "4. Guarda las capturas en: screenshots/"
echo ""
echo "5. Nombra los archivos según la guía en docs/GUIA_CAPTURAS_PANTALLA.md"
echo ""

# Crear estructura de carpetas
mkdir -p screenshots/{01-autenticacion,02-gestion-fcps,03-gestion-aulas,04-gestion-estudiantes,05-asistencias,06-reportes,07-diseno}

echo "✅ Estructura de carpetas creada en screenshots/"
echo ""
echo "Para tomar capturas en Linux:"
echo "  - Print Screen: Captura completa"
echo "  - Shift + Print Screen: Seleccionar área"
echo "  - Flameshot: flameshot gui (recomendado)"
echo ""
echo "Ver docs/GUIA_CAPTURAS_PANTALLA.md para más detalles"

